# Generated by Django 5.0.3 on 2024-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_count_variant_inventory_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='inventory',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
