# Generated by Django 5.0.3 on 2024-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variant_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'نوع', 'verbose_name_plural': 'انواع '},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.AddField(
            model_name='variant',
            name='type',
            field=models.ManyToManyField(related_name='variant_type', to='product.type', verbose_name='نوع محصول'),
        ),
    ]
