# Generated by Django 5.0.3 on 2024-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_color_type_alter_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ManyToManyField(related_name='variant_size', to='product.size', verbose_name='سایز محصول'),
        ),
    ]
