# Generated by Django 5.0.3 on 2024-05-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_variant_size_variant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='size',
            field=models.ManyToManyField(related_name='supply_size', to='product.size', verbose_name='اندازه محصول'),
        ),
        migrations.AddField(
            model_name='supply',
            name='type',
            field=models.ManyToManyField(related_name='supply_types', to='product.type', verbose_name='مدل محصول'),
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='type',
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_size', to='product.size', verbose_name='سایز محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_type', to='product.type', verbose_name='نوع محصول'),
            preserve_default=False,
        ),
    ]
