# Generated by Django 5.0.3 on 2024-05-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_supply_size_supply_type_remove_variant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveBigIntegerField(blank=True, default=1, verbose_name='موقعیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsets', to='product.category', verbose_name='زیردسته'),
        ),
    ]
