# Generated by Django 4.2.7 on 2024-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_position_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'دسته بندی ', 'verbose_name_plural': 'دسته بندی ها '},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام مدل'),
        ),
    ]
