# Generated by Django 4.2.7 on 2024-05-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_options_alter_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی ', 'verbose_name_plural': 'دسته بندی ها '},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='children',
        ),
        migrations.RemoveField(
            model_name='category',
            name='position',
        ),
    ]
