# Generated by Django 5.0.3 on 2024-05-12 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='supply_size', to='product.size', verbose_name='اندازه محصول'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='supply_types', to='product.type', verbose_name='مدل محصول'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_size', to='product.size', verbose_name='سایز محصول'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_type', to='product.type', verbose_name='نوع محصول'),
        ),
    ]
