# Generated by Django 5.0.3 on 2024-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_supply_size_alter_supply_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='size',
            field=models.ManyToManyField(related_name='supply_size', to='product.size', verbose_name='اندازه محصول'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='type',
            field=models.ManyToManyField(related_name='supply_types', to='product.type', verbose_name='مدل محصول'),
        ),
    ]
