# Generated by Django 5.0.3 on 2024-04-13 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 20, 40, 49, 501893, tzinfo=datetime.timezone.utc)),
        ),
    ]
