# Generated by Django 5.0.3 on 2024-04-23 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 9, 5, 42, 498421, tzinfo=datetime.timezone.utc)),
        ),
    ]
