# Generated by Django 5.0.3 on 2024-04-28 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cart_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 9, 11, 59, 876587, tzinfo=datetime.timezone.utc)),
        ),
    ]
