# Generated by Django 4.2.7 on 2024-05-08 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_alter_cart_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 18, 58, 57, 383376, tzinfo=datetime.timezone.utc)),
        ),
    ]
