# Generated by Django 4.2.7 on 2024-05-09 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_alter_cart_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 17, 58, 36, 395454, tzinfo=datetime.timezone.utc)),
        ),
    ]
