# Generated by Django 5.0.3 on 2024-05-14 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_alter_cart_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 19, 47, 45, 231677, tzinfo=datetime.timezone.utc)),
        ),
    ]
