# Generated by Django 5.0.3 on 2024-04-23 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 9, 5, 42, 498421, tzinfo=datetime.timezone.utc)),
        ),
    ]
