# Generated by Django 5.0.3 on 2024-04-26 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_create_at_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 9, 54, 17, 215855, tzinfo=datetime.timezone.utc)),
        ),
    ]
