# Generated by Django 5.0.3 on 2024-04-28 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 17, 33, 56, 407464, tzinfo=datetime.timezone.utc)),
        ),
    ]
