# Generated by Django 5.0.3 on 2024-04-29 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 4, 25, 27, 556962, tzinfo=datetime.timezone.utc)),
        ),
    ]
