# Generated by Django 5.0.3 on 2024-04-30 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 5, 34, 56, 366317, tzinfo=datetime.timezone.utc)),
        ),
    ]
