# Generated by Django 5.0.3 on 2024-05-11 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 5, 14, 45, 227379, tzinfo=datetime.timezone.utc)),
        ),
    ]
