# Generated by Django 5.0.3 on 2024-05-15 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 5, 0, 13, 800076, tzinfo=datetime.timezone.utc)),
        ),
    ]
