# Generated by Django 5.0.3 on 2024-05-16 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 12, 33, 27, 23935, tzinfo=datetime.timezone.utc)),
        ),
    ]
